### ISSUE TITLE
NullPointerException when using cache:render TagLib 

### ISSUE THREAD

**Issue by bwagner5** [grails-plugins/grails-cache#20]
I'm receiving a NullPointerException here: https://github.com/grails-plugins/grails-cache/blob/master/grails-app/taglib/grails/plugin/cache/CacheTagLib.groovy#L116

I assume there's an issue where groovyPagesTemplateRenderer is not being injected properly.  

My code looks like this: `<cache:render template="path/to/template" key="1000" />`

**Comment by ctoestreich** [comment]
I also hit this error.  Here is more details.

The Cache tag passes in webRequest to the following method:

``` groovy
protected String calculateFullKey(String templateName, String contextPath, String pluginName) {
		GrailsWebRequest webRequest = RequestContextHolder.currentRequestAttributes()
		String uri = webRequest.attributes.getTemplateUri(templateName, webRequest.request)

		GroovyPageTemplate t = groovyPagesTemplateRenderer.findAndCacheTemplate(
			webRequest, pageScope, templateName, contextPath, pluginName, uri)
		if (!t) {
			throwTagError("Template not found for name [$templateName] and path [$uri]")
		}

		t.metaInfo.pageClass.name
	}
```

The issue is that when it gets down into core and runs this method it can't find the artefact and throws NPE.

```
 public GroovyPageScriptSource findTemplateInBinding(Object controller, String pluginName, String templateName, TemplateVariableBinding binding) {
        if (controller == null) {
            GrailsWebRequest webRequest = GrailsWebRequest.lookup();
            if (webRequest == null) {
                return findPageInBinding(pluginName, uriService.getAbsoluteTemplateURI(templateName), binding);
            }
            return findPageInBinding(pluginName, uriService.getTemplateURI(webRequest.getControllerName(), templateName), binding);
        }
        final GrailsControllerClass controllerClass = (GrailsControllerClass)grailsApplication.getArtefact(ControllerArtefactHandler.TYPE, GrailsNameUtils.getFullClassName(controller.getClass()) );

        String templateURI;
        final String ns = controllerClass.getNamespace(); //This causes NPE due to controllerClass == null
        ....
}
```


<img width="597" alt="screen shot 2015-12-11 at 9 38 32 am" src="https://cloud.githubusercontent.com/assets/691357/11747876/36f979c0-9feb-11e5-81fe-25ec232ed1fa.png">
<img width="1150" alt="screen shot 2015-12-11 at 9 37 33 am" src="https://cloud.githubusercontent.com/assets/691357/11747878/36fc1856-9feb-11e5-92f3-c7f543b63479.png">
<img width="1121" alt="screen shot 2015-12-11 at 9 37 22 am" src="https://cloud.githubusercontent.com/assets/691357/11747877/36fb71e4-9feb-11e5-9ad0-c4a9f5a62211.png">
<img width="1151" alt="screen shot 2015-12-11 at 9 36 58 am" src="https://cloud.githubusercontent.com/assets/691357/11747879/36fe00bc-9feb-11e5-84ef-e13df63bc813.png">

**Comment by ctoestreich** [comment]
@graemerocher I am not sure if this utimately is a problem with the way this plugin works or if there should be a NPE check in the findtemplateinbinding method.  Thoughts?

**Comment by graemerocher** [comment]
Yeah could probably do with a null check in there... pull requests welcome

**Comment by ctoestreich** [comment]
I will, but instead of getting my PR declined again :smile: I wanted to pick your brain on whether the plugin was doing the correct thing or grails-core needed the NPE check.

**Comment by graemerocher** [comment]
@ctoestreich :+1: :-D

**Comment by ctoestreich** [comment]
It looks like the plugin needs to change to call this method

```
 // required for binary compatibility: GRAILS-11598
    private Template findAndCacheTemplate(Object controller, GrailsWebRequest webRequest, GroovyPageBinding pageScope, String templateName,
            String contextPath, String pluginName, String uri) throws IOException {
        return findAndCacheTemplate(controller, pageScope, templateName, contextPath, pluginName, uri);
    }
```

It still might need a null check.  Will do both.
